# Generated by Django 4.2.5 on 2023-10-01 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("info", "0002_customer_liked_stock_1_customer_liked_stock_2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="industry",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="name",
        ),
        migrations.AddField(
            model_name="customer",
            name="graph_image",
            field=models.ImageField(blank=True, null=True, upload_to="user_graphs/"),
        ),
        migrations.AddField(
            model_name="customer",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="liked_stock_1",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="customer",
            name="liked_stock_2",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
