# Generated by Django 4.2.5 on 2023-10-04 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0003_remove_customer_industry_remove_customer_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="user",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="graph_image",
        ),
    ]
